### ISSUE TITLE
Unfinished sentence in codealong directions

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/sinatra-sessions#24]
"In this exercise, we'll be setting the :id key of the session hash equal to a value of..."

**Comment by atxrenegade** [comment]
May I suggest finishing this sentence with "...the user id"

**Comment by Sdcrouse** [comment]
Hi. It looks like they fixed this.

**Comment by rrcobb** [comment]
The sentence ([README.md line 54](https://github.com/learn-co-curriculum/sinatra-sessions/blame/master/README.md#L54)) is:

> In this exercise, we'll be setting the :id key of the session hash equal to a value of `1`.

I think there might be an issue with the display of the inline code block - if you are seeing the sentence end at 'of', then the `1` might not be displaying correctly. That line hasn't been updated since 2016, so I don't think we've fixed a typo - it could be that the rendering bug has been fixed, or that @Sdcrouse looked at the README, saw the `1` and assumed that it had been wrong and then updated.

Is anyone else seeing a bug in the display of this line? If so, please reopen the issue - it's not something that the curriculum team can fix directly, but we definitely want to escalate it to the engineering team.

**Comment by Sdcrouse** [comment]
It's been a while since I did this codealong. If I remember right, it rendered correctly. So, I'm guessing that some kind of rendering bug got fixed, like you said.
